---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: renovatebot
  namespace: apps
spec:
  interval: 15m
  chart:
    spec:
      chart: renovate
      version: '34.30.1'
      sourceRef:
        kind: HelmRepository
        name: renovatebot
        namespace: flux-system
      interval: 15m
  values: []
