---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: satisfactory
  namespace: apps
spec:
  interval: 15m
  chart:
    spec:
      chart: satisfactory
      version: '4.0.14'
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  values:
    env:
      MAXPLAYERS: 8
    persistence:
      config:
        enabled: true
        existingClaim: satisfactory
