---
# yaml-language-server: $schema=https://kubernetes-schemas.trux.dev/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app satisfactory
  namespace: apps
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.3.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      repository: wolveix/satisfactory-server
      tag: v1.4.5
    env:
      DATA_FOLDER: "config"
    service:
      main:
        type: LoadBalancer
        externalTrafficPolicy: Cluster
        loadBalancerIP: 192.168.0.53
        annotations:
          metallb.universe.tf/allow-shared-ip: satisfactory
        ports:
          http:
            enabled: false
            primary: false
          query:
            enabled: true
            port: 15777
            protocol: UDP
          beacon:
            enabled: true
            port: 15000
            protocol: UDP
          game:
            enabled: true
            port: 7777
            protocol: UDP
    persistence:
      config:
        enabled: true
        existingClaim: satisfactory
        mountPath: /config
      server-cache:
        enabled: true
        existingClaim: satisfactory-cache
        mountPath: /config/gamefiles
    probes:
      startup:
        enabled: false
      liveness:
        enabled: false
      readiness:
        enabled: false
