---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: apps
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: '0.2.2'
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    image:
      repository: openblocksdev/openblocks-ce
      tag: latest
    service:
      main:
        ports:
          http:
            port: 3000
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: traefik
        hosts:
          - host: openblocks.intropin.be
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: openblocks
                  namespace: apps
                  port: 3000
    persistence:
      config:
        enabled: true
        existingClaim: openblocks
        mountPath: "/openblocks-stacks"
