---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: automatisch
  namespace: apps
spec:
  interval: 60m
  chart:
    spec:
      chart: app-template
      version: '0.2.2'
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/automatisch/automatisch
      tag: 0.5.0
    service:
      main:
        ports:
          http:
            port: 3000
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: traefik
        hosts:
          - host: automatisch.intropin.be
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: automatisch
                  namespace: apps
                  port: 3000
    persistence:
      storage:
        enabled: true
        existingClaim: automatisch
        mountPath: /automatisch/storage
    env:
      HOST: localhost
      PORT: 3000
      APP_ENV: production
      WEB_APP_URL: https://automatisch.intropin.be
      POSTGRES_DATABASE: autmatisch
      POSTGRES_HOST: postgres-postgresql.databases.svc.cluster.local
      POSTGRES_USER: postgres
      POSGRES_PASSWORD: c3d0ZmExNjEyCg==
      REDIS_HOST: redis-master.databases.svc.cluster.local
      REDIS_PASSWORD: QmFlZGFpZ3UzcGhp 
      ENCRYPTION_KEY: 
      WEBHOOK_SECRET_KEY: 
      APP_SECRET_KEY:
