---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vikunja
  namespace: apps
spec:
  interval: 15m
  chart:
    spec:
      chart: vikunja
      version: '0.1.0'
      sourceRef:
        kind: HelmRepository
        name: yan-solo
        namespace: flux-system
      interval: 15m
  values:
    postgresql:
      enabled: false

    config: |-
      service:
        jwtsecret: "myVeryComplexJWTSecret"
        enableregistration: false
      database:
        type: "psql"
        user: "postgres"
        password: "changeme"
        host: "postgres-postgresql.databases.svc.cluster.local"
        database: "vikunja"

    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: traefik
        hosts:
          - host: vikunja.intropin.be
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: vikunja
                  namespace: apps
                  port: 8080
