---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vikunja
  namespace: apps
spec:
  interval: 15m
  chart:
    spec:
      chart: vikunja
      version: '0.1.0'
      sourceRef:
        kind: HelmRepository
        name: yan-solo
        namespace: flux-system
      interval: 15m
  values:
    postgresql:
      enabled: false

    vikunja:
      config: |-
        service:
          jwtsecret: "myVeryComplexJWTSecret"
          enableregistration: false
          timezone: "Europe/Brussels"
        database:
          type: "postgres"
          user: "postgres"
          password: "c3d0ZmExNjEyCg=="
          host: "postgres-postgresql.databases.svc.cluster.local"
          database: "vikunja"
          port: 5432

    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: traefik
        hosts:
          - host: vikunja.intropin.be
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: vikunja
                  namespace: apps
                  port: 8080
