---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bjw-s
  # This is deployed in flux-system because it might
  # be usefull for multiple namespaces
  namespace: flux-system
spec:
  interval: 15m
  url: http://bjw-s.github.io/helm-charts
