---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: dysnix
  # This is deployed in flux-system because it might
  # be usefull for multiple namespaces
  namespace: flux-system
spec:
  interval: 15m
  url: https://dysnix.github.io/charts
