apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: uptime-kuma
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: '0.2.2'
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    image:
      repository: registry.hub.docker.com/louislam/uptime-kuma
      tag: 1.19.3
    service:
      main:
        ports:
          http:
            port: 3001
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: traefik
        hosts:
          - host: uptime-kuma.intropin.be
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: uptime-kuma
                  namespace: monitoring
                  port: 3001
          - host: status.intropin.be
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: uptime-kuma
                  namespace: monitoring
                  port: 3001
    persistence:
      data:
        enabled: true
        existingClaim: uptime-kuma-config
        mountPath: /app/data/
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: false
