---
apiVersion: v1
kind: Pod
metadata:
  name: csexpdino
  namespace: monitoring
  labels:
    app: csexpdino
spec:
  containers:
  - name: csexpdino
    image: kinduff/csgo_exporter:1.4.2
    ports:
      - containerPort: 7357
        name: csexpdino-svc
    env:
    - name: FETCH_INVENTORY
      value: "true"
    - name: STEAM_ID
      value: "76561198122354233"
    - name: HTTP_PORT
      value: "7357"
    - name: STEAM_API_KEY
      valueFrom:
        secretKeyRef:
          name: steam-key-main
          namespace: monitoring
          key: apiKey

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: csexpdino
  annotations:
    alpha.monitoring.coreos.com/non-namespaced: "true"
  name: csexpdino
  namespace: monitoring
spec:
  ports:
  - name: csexpdino-svc
    port: 7357
    targetPort: csexpdino-svc
    protocol: TCP
  selector:
    app: csexpdino

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: csexpdino
  namespace: monitoring
  labels:
    app: csexpdino
spec:
  selector:
    matchLabels:
      app: csexpdino
  endpoints:
    - port: csexpdino-svc
      interval: 1m