---
apiVersion: v1
kind: Pod
metadata:
  name: csexpterra
  namespace: monitoring
  labels:
    app: csexpterra
spec:
  containers:
  - name: csexpterra
    image: kinduff/csgo_exporter:1.4.2
    ports:
      - containerPort: 7358
        name: csexpterra-svc
    env:
    - name: FETCH_INVENTORY
      value: "true"
    - name: STEAM_ID
      value: "76561198051169853"
    - name: HTTP_PORT
      value: "7358"
    - name: STEAM_API_KEY
      valueFrom:
        secretKeyRef:
          name: steam-key-main
          namespace: monitoring
          key: apiKey

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: csexpterra
  annotations:
    alpha.monitoring.coreos.com/non-namespaced: "true"
  name: csexpterra
  namespace: monitoring
spec:
  ports:
  - name: csexpterra-svc
    port: 7358
    targetPort: csexpterra-svc
    protocol: TCP
  selector:
    app: csexpterra

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: csexpterra
  namespace: monitoring
  labels:
    app: csexpterra
spec:
  selector:
    matchLabels:
      app: csexpterra
  endpoints:
    - port: csexpterra-svc
      interval: 1m