---
apiVersion: v1
kind: Pod
metadata:
  name: csexpzeds
  namespace: monitoring
  labels:
    app: csexpzeds
spec:
  containers:
  - name: csexpzeds
    image: kinduff/csgo_exporter:1.4.2
    ports:
      - containerPort: 7357
        name: csexpzeds-svc
    env:
    - name: FETCH_INVENTORY
      value: "true"
    - name: STEAM_ID
      value: "76561198122354233"
    - name: HTTP_PORT
      value: "7358"
    - name: STEAM_API_KEY
      valueFrom:
        secretKeyRef:
          name: steam-key-main
          namespace: monitoring
          key: apiKey

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: csexpzeds
  annotations:
    alpha.monitoring.coreos.com/non-namespaced: "true"
  name: csexpzeds
  namespace: monitoring
spec:
  ports:
  - name: csexpzeds-svc
    port: 7358
    targetPort: csexpzeds-svc
    protocol: TCP
  selector:
    app: csexpzeds

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: csexpzeds
  namespace: monitoring
  labels:
    app: csexpzeds
spec:
  selector:
    matchLabels:
      app: csexpzeds
  endpoints:
    - port: csexpzeds-svc
      interval: 1m

