---
apiVersion: v1
kind: Pod
metadata:
  name: csgoexp
  namespace: monitoring
  labels:
    app: csgoexp
spec:
  containers:
  - name: csgoexp
    image: kinduff/csgo_exporter:1.4.2
    ports:
      - containerPort: 7355
        name: csgoexp-svc
    env:
    - name: FETCH_INVENTORY
      value: "true"
    - name: STEAM_ID
      value: "76561198053474890"
    - name: STEAM_API_KEY
      valueFrom:
        secretKeyRef:
          name: steam-key-main
          namespace: monitoring
          key: apiKey

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: csgoexp
  annotations:
    alpha.monitoring.coreos.com/non-namespaced: "true"
  name: csgoexp
  namespace: monitoring
spec:
  ports:
  - name: csgoexp-svc
    port: 7355
    targetPort: csgoexp-svc
    protocol: TCP
  selector:
    app: csgoexp

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: csgoexp
  namespace: monitoring
  labels:
    app: csgoexp
spec:
  selector:
    matchLabels:
      app: csgoexp
  endpoints:
    - port: csgoexp-svc
      interval: 1m