---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: jellyfin
  namespace: monitoring
  labels:
    app.kubernetes.io/name: jellyfin
spec:
  selector:
    matchLabels:
       app.kubernetes.io/name: jellyfin
  endpoints:
    - port: jellyfin
      interval: 1m