clusterName: echel
talosVersion: v1.3.3
kubernetesVersion: v1.26.0
endpoint: https://192.168.0.40:6443
domain: cluster.local
allowSchedulingOnMasters: true
clusterPodNets:
  - 10.244.0.0/16
clusterSvcNets:
  - 10.96.0.0/12
cniConfig:
  name: flannel
nodes:
  - hostname: master01
    ipAddress: 192.168.0.40
    installDisk: /dev/sda
    controlPlane: true
    nameservers:
      - 1.1.1.1
      - 8.8.8.8
    networkInterfaces:
      - interface: eth0
        addresses:
          - 192.168.0.40/24
        mtu: 1500
        routes:
          - network: 0.0.0.0/0
            gateway: 192.168.0.1
    patches:
      - |-
        machine:
          kubelet:
            extraMounts:
              - destination: /var/mnt/disk
                type: bind
                source: /var/mnt/disk
                options:
                  - bind
                  - rshared
                  - rw
      - |-
        - op: add
          path: /machine/disks
          value:
            - device: /dev/sdb
              partitions:
                - mountpoint: /var/mnt/disk
