---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgres
  namespace: databases
spec:
  interval: 15m
  chart:
    spec:
      chart: postgresql
      version: '12.1.2'
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    global:
      postgresql:
        auth:
          enablePostgresUser: true
          existingSecret: postgresql-secret
          secretKeys:
            adminPasswordKey: "postgres-password"

    primary:
      persistence:
        enabled: true
        existingClaim: postgresql
