# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: toolbox
  namespace: core
  labels:
    app: toolbox
spec:
  selector:
    matchLabels:
      app: toolbox
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: toolbox
    spec:
      containers:
      - name: toolbox
        image: ghcr.io/yan-solo/toolbox:v0.1.3
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        command: ["/bin/sh", "-c", "--"]
        args: ["while true; do sleep 30; done;"]
        volumeMounts:
        - name: local-storage
          mountPath: /mnt/disk
      volumes:
        - name: local-storage
          hostPath:
            path: /var/mnt/disk
      restartPolicy: Always
