---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tandoor
  namespace: apps
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: '0.2.2'
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    image:
      repository: registry.hub.docker.com/vabene1111/recipes
      tag: 1.4.5

    envFrom:
      - secretRef:
          name: tandoor-config

    persistence:
      staticfiles:
        enabled: true
        existingClaim: tandoor-staticfiles
      mediafiles:
        enabled: true
        existingClaim: tandoor-mediafiles

    service:
      main:
        ports:
          http:
            port: 8080

    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: false

    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: traefik
        hosts:
          - host: tandoor.intropin.be
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: tandoor
                  namespace: apps
                  port: 8080
