---
# https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
  name: tandoor-config
  namespace: apps
type: Opaque
stringData:
    DEBUG: "0"
    SQL_DEBUG: "0"
    ALLOWED_HOSTS: "*"
    SECRET_KEY: "CjfynP42oc33MSbSPYn9qkvHeUVD6KJjf2uNqKWa0nYAoPkuFb"
    TIMEZONE: "Europe/Brussels"
    DB_ENGINE: "django.db.backends.postgresql"
    POSTGRES_HOST: "postgres-postgresql.databases.svc.cluster.local"
    POSTGRES_PORT: "5432"
    POSTGRES_USER: "postgres"
    POSTGRES_PASSWORD: "c3d0ZmExNjEyCg=="
    POSTGRES_DB: "tandoor"
    FRACTION_PREF_DEFAULT: "0"
    COMMENT_PREF_DEFAULT: "1"
    SHOPPING_MIN_AUTOSYNC_INTERVAL: "5"
    GUNICORN_MEDIA: "0"
    REVERSE_PROXY_AUTH: "0"
    DB_PORT_3306_TCP_PROTO: "5432"
