---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: standardnotes-redis
  labels:
    claimer: redis
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  nfs:
    path: /mnt/stor0/standardnotes-redis
    server: 192.168.0.250

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: standardnotes-mysql
  labels:
    claimer: mysql
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  nfs:
    path: /mnt/stor0/standardnotes-mysql
    server: 192.168.0.250

---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    claimer: import
  name: standardnotes-import
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  nfs:
    path: /mnt/stor0/standardnotes-import
    server: 192.168.0.250
