---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nfs-client-provisioner
  namespace: core
spec:
  interval: 15m
  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      version: '4.0.17'
      sourceRef:
        kind: HelmRepository
        name: nfs-client-provisioner
        namespace: flux-system
      interval: 15m
  values:
    nfs:
      server: "192.168.0.250"
      path: "/mnt/stor0"
