apiVersion: v1
kind: Secret
metadata:
  name: server
  namespace: apps
stringData:
  pg_host: "postgres-postgresql.svc.databases.cluster.local"
  pg_db: "tooljet"
  pg_user: "postgres"
  pg_password: "c3d0ZmExNjEyCg=="
  pg_port: "5432"
