apiVersion: v1
kind: Service
metadata:
  name: tooljet
  namespace: apps
spec:
  type: ClusterIP
  selector:
    component: tooljet
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      name: http
