apiVersion: v1
kind: Service
metadata:
  name: tooljet
spec:
  type: LoadBalancer
  selector:
    component: tooljet
  ports:
    - protocol: TCP
      port: 443
      targetPort: 3000
      name: https
