---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: muse
  namespace: apps
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: '0.2.2'
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/codetheweb/muse
      tag: v2.1.7
    ingress:
      main:
        enabled: false
    persistence:
      config:
        enabled: true
        existingClaim: muse
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: false

