---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: muse
  namespace: apps
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: '0.2.2'
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    image:
      repository: registry.hub.docker.com/codetheweb/muse
      tag: 1a61d87333f2ca4f89fa7cb8bfffb71fca220092
    env:
      DISCORD_TOKEN: MTA2MzA5OTM3MjM3MzU0MDkwNA.Gl3Xok.tRrHqmo-lQ1fboSMwjmgBkKGK_EQTi-YPQkCwA
      SPOTIFY_CLIENT_ID: 2561614d1fdf46f983288c3f2c3f201c
      SPOTIFY_CLIENT_SECRET: 50c8e921d7bc44d1af5213baec9b3b1f
    service:
      main:
        ports:
          http:
            port: 80
    ingress:
      main:
        enabled: false
    persistence:
      config:
        enabled: true
        existingClaim: muse
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: false

