---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: n8n
  namespace: apps
spec:
  interval: 60m
  chart:
    spec:
      chart: n8n
      version: '0.10.0'
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: open-8gears
        namespace: flux-system
  values:
    n8n:
      encryption_key: "phuJ9su4"
    config:
      database:
        postgresdb:
          database: "n8n"
          host: postgres-postgresql.svc.databases.cluster.local 
          user: "postgres"
          password: "c3d0ZmExNjEyCg=="
          ssl:
            rejectUnauthorized: false
      generic:
        timezone: "Europe/Brussels"
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: traefik
      hosts:
        - host: n8n.intropin.be
          paths:
            - path: /
    persistence:
      enabled: true
      existingClaim: n8n 
      mountPath: /config
    extraEnv: 
      WEBHOOK_TUNNEL_URL: "https://n8n.intropin.be/"
