---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: n8n
  namespace: apps
spec:
  interval: 15m
  chart:
    spec:
      chart: n8n
      version: '0.8.0'
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: open-8gears
        namespace: flux-system
  values:
    config:
      database:
        type: postgresdb
        postgresdb:
          host: postres-postgresql.databases.svc.cluster.local
    secret:
      database:
        postgresdb:
          password: 'c3d0ZmExNjEyCg=='
    extraEnv:
      N8N_ENCRYPTION_KEY: 'some_random_string'
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: traefik
        hosts:
          - host: n8n.intropin.be
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: n8n
                  namespace: apps
                  port: 8123
