---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: n8n
  namespace: apps
spec:
  interval: 60m
  chart:
    spec:
      chart: app-template
      version: '0.2.2'
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    image:
      repository: n8nio/n8n
      tag: latest
    service:
      main:
        ports:
          http:
            port: 5678
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: traefik
        hosts:
          - host: n8n.intropin.be
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: n8n
                  namespace: apps
                  port: 5678
    persistence:
      storage:
        enabled: true
        existingClaim: n8n
        mountPath: /home/node/.n8n 
    env:
      - name: N8N_BASIC_AUTH_ACTIVE
        value: true
      - name: N8N_BASIC_AUTH_USER
        value: "jan"
      - name: N8N_BASIC_AUTH_PASSWORD
        value: "swtfa1612"
      - name: N8N_HOST
        value: "n8n.intropin.be"
      - name: N8N_PORT
        value: "5678"
      - name: N8N_PROTOCOL
        value: "https"
      - name: NODE_ENV
        value: "roduction"
      - name: WEBHOOK_URL
        value: "https://n8n.intropin.be/"
      - name: GENERIC_TIMEZONE
        value: "Europe/Brussels"
      - name: DB_TYPE
        value: "postgresdb"
      - name: DB_POSTGRESDB_DATABASE
        value: "n8n"
      - name: DB_POSTGRESDB_HOST
        value: "postgres-postgresql.databases.svc.cluster.local"
      - name: DB_POSTGRESDB_PORT
        value: "5432"
      - name: DB_POSTGRESDB_USER
        value: "postgres"
      - name: DB_POSTGRESDB_PASSword
        value: "c3d0ZmExNjEyCg=="
      - name: N8N_EDITOR_BASE_URL
        value: "https://n8n.intropin.be"
      - name: N8N_LOG_LEVEL
        value: debug
      - name: DB_LOGGING_ENABLED
        value: true
      - name: DB_LOGGING_OPTIONS
        value: log
