---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: n8n
  namespace: apps
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: '0.2.2'
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    image:
      repository: n8nio/n8n
      tag: 0.212.1
    env:
      DB_TYPE: postgresdb
      DB_POSTGRESDB_DATABASE: n8n
      DB_POSTGRESDB_HOST: postgres-postgresql.svc.databases.cluster.local
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_SCHEMA: public
      DB_POSTGRESDB_PASSWORD: "c3d0ZmExNjEyCg=="
      N8N_LISTEN_ADDRESS: "0.0.0.0"
      N8N_LOG_LEVEL: "debug"
      N8N_LOG_OUTPUT: "console"
    service:
      main:
        ports:
          http:
            port: 8080
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: traefik
        hosts:
          - host: n8n.intropin.be
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: n8n
                  namespace: apps
                  port: 8080
    persistence:
      config:
        enabled: true
        existingClaim: n8n
        mountPath: /home/node/.n8n
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: false

