---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: n8n
  namespace: apps
spec:
  interval: 60m
  chart:
    spec:
      chart: app-template
      version: '0.2.2'
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    image:
      repository: n8nio/n8n
      tag: latest
    service:
      main:
        ports:
          http:
            port: 5678
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: traefik
        hosts:
          - host: n8n.intropin.be
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: n8n
                  namespace: apps
                  port: 5678
    persistence:
      storage:
        enabled: true
        existingClaim: n8n
        mountPath: /home/node/.n8n 
    env:
      - N8N_BASIC_AUTH_ACTIVE: true
      - N8N_BASIC_AUTH_USER: jan
      - N8N_BASIC_AUTH_PASSWORD: swtfa1612
      - N8N_HOST: n8n.intropin.be
      - N8N_PORT: 5678
      - N8N_PROTOCOL: https
      - NODE_ENV=: roduction
      - WEBHOOK_URL: https://n8n.intropin.be/
      - GENERIC_TIMEZONE: Europe/Brussels
      - DB_TYPE: postgresdb
      - DB_POSTGRESDB_DATABASE: n8n
      - DB_POSTGRESDB_HOST: postgres-postgresql.databases.svc.cluster.local
      - DB_POSTGRESDB_PORT: 5432
      - DB_POSTGRESDB_USER: postgres
      - DB_POSTGRESDB_PASSword: c3d0ZmExNjEyCg==
      - N8N_EDITOR_BASE_URL: https://n8n.intropin.be
