apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sabnzbd
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: '0.2.2'
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/onedr0p/sabnzbd
      tag: 3.7.0
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
    persistence:
      config:
        enabled: true
        existingClaim: sabnzbd-config
      media:
        enabled: true
        existingClaim: nfs-media-pvc
        mountPath: "/mnt/media"

    env:
      HOST_WHITELIST_ENTRIES: sabnzbd.intropin.be
        
    service:
      main:
        ports:
          http:
            port: &port 8080
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: traefik
          traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
          traefik.ingress.kubernetes.io/router.tls: 'true'
          traefik.ingress.kubernetes.io/router.tls.certresolver: cloudflare
        hosts:
          - host: sabnzbd.intropin.be
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: sabnzbd
                  namespace: media
                  port: *port

    resources:
      requests:
        memory: 4Gi


