---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wikijs
  namespace: apps
spec:
  interval: 15m
  chart:
    spec:
      chart: wiki
      version: '2.2.0'
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: wikijs
        namespace: flux-system
  values:
    ingress:
      hosts:
        - host: wikijs.intropin.be
          paths:
            - path: /
              pathType: Prefix
    postgresql:
      persistence:
        existingClaim: "wikijs"
