
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: appsmith
  namespace: apps
spec:
  interval: 15m
  chart:
    spec:
      chart: appsmith
      version: '2.0.0'
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: appsmith
        namespace: flux-system
  values:
    applicationConfig:
      APPSMITH_DISABLE_TELEMETRY: true
      APPSMITH_REDIS_URL: 'redis://redis-master.databases.svc.cluster.local:6379'
      APPSMITH_MONGODB_URI: 'mongodb+srv://root:c3d0ZmExNjEyCg@mongodb.databases.svc.cluster.local/appsmith'
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: traefik
        hosts:
          - host: appsmith.intropin.be
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: appsmith
                  namespace: apps
                  port: 80
    persistence:
      enabled: false
    redis:
      enabled: false
    mongodb:
      enabled: false
