---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis
  namespace: databases
spec:
  interval: 15m
  chart:
    spec:
      chart: redis
      version: '17.8.2'
      interval: 60m
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    architecture: standalone

    auth:
      existingSecret: redis-secret
      secretKeys:
        adminPasswordKey: "redis-password"
      usePasswordFiles: true

    master:
      persistence:
        enabled: true
        existingClaim: redis
