---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: weave-gitops
  namespace: flux-system
spec:
  interval: 15m 
  chart:
    spec:
      chart: weave-gitops
      version: 4.0.12
      interval: 15m 
      sourceRef:
        kind: HelmRepository
        name: weave-gitops
        namespace: flux-system
  values:
    podAnnotations:
      secret.reloader.stakater.com/reload: weave-gitops-secrets

    logLevel: info

    adminUser:
      create: true
      username: &admin_user admin

    networkPolicy:
      create: false

    metrics:
      enabled: true

    rbac:
      create: true
      impersonationResourceNames:
        - *admin_user
      additionalRules:
        - apiGroups:
            - "infra.contrib.fluxcd.io"
          resources:
            - "terraforms"
          verbs:
            - "get"
            - "list"
            - "patch"

    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: traefik
        hosts:
          - host: weave.intropin.be
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: weave-gitops
                  namespace: flux-system
                  port: 9001
