---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: budibase
  namespace: apps
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: '0.2.2'
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    image:
      repository: budibase/budibase
      tag: latest
    service:
      main:
        ports:
          http:
            port: 80
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: traefik
        hosts:
          - host: budibase.intropin.be
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: budibase
                  namespace: apps
                  port: 80
    persistence:
      data:
        enabled: true
        existingClaim: budibase
        mountPath: /data
