---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: budibase
  namespace: budibase
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: '0.2.11'
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: budibase
        namespace: flux-system
  values:
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: traefik
      hosts:
        - host: budibase.intropin.be
          paths:
            - path: /
              pathType: Prefix
              service:
                name: budibase
                namespace: apps
                port: 10000
