---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mongodb 
  namespace: databases
spec:
  interval: 15m
  chart:
    spec:
      chart: mongodb 
      version: '13.9.4'
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    architecture: "replicaset"
    auth:
      enabled: true
      existingSecret: mongodb-secret
      secretKeys:
        rootUser: "mongodb-user"
        rootPassword: "mongodb-password"
      usePasswordFiles: true

    primary:
      persistence:
        enabled: true
        existingClaim: mongodb 
