# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.26.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: grafana-secret
    labels:
        app.kubernetes.io/name: grafana
type: Opaque
stringData:
    gf_security_admin_user: ENC[AES256_GCM,data:HXWlrMthMQ==,iv:krnoPlP4hL07CjO8PTg+VQSFvzVsTAr+lARM8FSKUn4=,tag:XbVmDo3xJRyN5iEWvTDdnQ==,type:str]
    gf_security_admin_password: ENC[AES256_GCM,data:1R9QC7TIkJ1PzcimtQ==,iv:Urfy8JxuYBTqUBtCftXEVLb2WqqK/haASV+jfYcsmmI=,tag:trx7f7U5qihoTxO2qOPgbg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zeqkpfz7e3s207ynea0z0auc0mrct0pc7w4sh6j3d0c4qac3dahqj9ufdg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4MEJMeEtlUXVYK3JxOUtw
            c2pEd0FoM21LNmhmRXhMbzFwdG1aL2tnMmdVCld2QUtBenlxWVBGbG5JaEZQalQw
            cXBnaDVGRWhkLzhlOHZhbzY5Zk83T3cKLS0tIDZmNFg5aERud0hVRFVVOHQ1b0E1
            TE5lSmJtT3o4bmNIV2lnbUxUZ2phRHMK1vAs3Aukg6/05GGSgMxaQVm46xfVaMGE
            w7Zf1Rd9Io6lT776/MlHxjyqTuHA++9ibPkHhJ5AUu7tudNj5Duh4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-21T05:53:36Z"
    mac: ENC[AES256_GCM,data:/iALQFAHAa2evN1329LRsgjXJtpQaLUkyJ/dFPdnDiZCRY8XOrrb2Xng79ClzOxIIDYD+XubR1jkwGTsDS4RQ8OPpxp1pBmIIh4nA6ZeTON6jwipmQdzfL2eqNqS3k3PIoUdf32U02JPsIeqU9Nrnj8bFKaN8DUkts3pC++AIdM=,iv:97rxnvx64DnUxmZkjxUrBHB6TISQyIV2xdLvZvv4VH0=,tag:OZKaTzeIf8b345LzATMg2Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|caBundle)$
    version: 3.7.3
