---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: changedetection
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: '0.2.2'
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/dgtlmoon/changedetection.io
      tag: 0.40.0.4
    service:
      main:
        ports:
          http:
            port: 5000
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: traefik
        hosts:
          - host: changedetection.intropin.be
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: changedetection
                  namespace: monitoring
                  port: 5000
    persistence:
      data:
        enabled: true
        existingClaim: changedetection
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: false

